<?php

namespace AppBundle\Repository;

/**
 * DifficultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DifficultyRepository extends \Doctrine\ORM\EntityRepository
{
}
