<?php

namespace AppBundle\Repository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getScoreByEvaluationIdAndCandidatId($evanuationId, $candidatId)
    {
        $qb = $this->createQueryBuilder('s')
        ->elect('s.id')

        ->leftJoin('e.author', 'a')
        ->leftJoin('e.difficulty', 'd')
        ->leftJoin('e.status', 's')
        ->leftJoin('e.questions', 'q')
        ->leftJoin('q.topic', 't')
        ->leftJoin('q.level', 'l')
        ->where('e.id = :id')
        ->setParameter(':id', $id, \PDO::PARAM_INT)
        ->orderBy('t.name', 'ASC')
        ->addOrderBy('l.name', 'ASC');
         
        return $qb->getQuery()->getSingleResult();
    }
}