app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_index:
    resource: "@AppBundle/Resources/config/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
