app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_index:
    resource: "@AppBundle/Resources/config/routing.yml"
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security_logout:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
