# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    appbundle.evaluation:
        class: AppBundle\Service\EvaluationService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        
    appbundle.user:
        class: AppBundle\Service\UserService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            
    appbundle.question:
        class: AppBundle\Service\QuestionService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    appbundle.json.encoder:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

    appbundle.object.normaliser: 
        class: 'Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
    
    appbundle.object.serializer: 
        class: AppBundle\Service\CustumerSerializer
        arguments:
            - ['@appbundle.object.normaliser']
            - ['@appbundle.json.encoder']

    appBundle.manage.candidate.evaluation:
        class: AppBundle\Service\ManageCandidateEvaluation
        arguments:
            #entityManager: "@doctrine.orm.entity_manager"
            - '@doctrine.orm.entity_manager'
            - '@appbundle.object.serializer'
            - '@session'