# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    appbundle.evaluation:
        class: AppBundle\Service\EvaluationService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        
    appbundle.user:
        class: AppBundle\Service\UserService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            
    appbundle.question:
        class: AppBundle\Service\QuestionService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"